bot_token:
bot_id:
bot_secret:
admin_id:
support_guild:
log_channel:
invite_link:
redirect_url:
origin_url:

db_host:
db_port:
db_db:
db_user:
db_password:

lavalink_nodes:
    lavalink_1:
        host:
        port:
        password:
    lavalink_2:
        host:
        port:
        password:
